SmartToothWebProject/SmartTooth/Models/Dentist.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace SmartTooth.Models
{
    public class Dentist
    {


        public Guid Id { get; set; }

        [StringLength(50, ErrorMessage = "{0} length must be between {2} and {1}.", MinimumLength = 3)]
        [Required(ErrorMessage = "Please enter a  Name")]
        public string Name { get; set; }

        [StringLength(50, ErrorMessage = "{0} length must be between {2} and {1}.", MinimumLength = 3)]
        [Required(ErrorMessage = "Please enter a  LastName")]
        public string LastName { get; set; }

        [Phone]
        [Required(ErrorMessage = "Please enter a  Number")]
        public string Number { get; set; }

        [Url]
        [Required(ErrorMessage = "Please enter a  FacebookUrl")]
        public string FacebookUrl { get; set; }

        [StringLength(1000, ErrorMessage = "{0} length must be between {2} and {1}.", MinimumLength = 6)]
        [Required(ErrorMessage = "Please enter a  Specialization")]
        public string Specialization { get; set; }

        [EmailAddress(ErrorMessage = "Please enter a  Email")]
        [Required(ErrorMessage = "Please enter a  Email")]
        public string Email { get; set; }

        [StringLength(1000, ErrorMessage = "{0} length must be between {2} and {1}.", MinimumLength = 6)]
        [Required(ErrorMessage = "Please enter a  Description")]
        public string Description { get; set; }
        
        public double Popularity { get; set; }
    }
}

SmartToothWebProject/SmartTooth/Models/ErrorViewModel.cs
using System;

namespace SmartTooth.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SmartToothWebProject/SmartTooth/Controllers/DentistController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.DependencyInjection;
using SmartTooth.Models;
using SmartTooth.Services.Dentist;

namespace SmartTooth.Controllers
{
    public class DentistController : Controller
    {
        private IDentistService _dentist;

        public DentistController(IDentistService dentist)
        {
            _dentist = dentist;
        }

        public IActionResult Index()
        {
            ViewBag.MyModel = DateTime.Now; ;
            return View();
        }

        [HttpGet]
        public IActionResult CreateDentist()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateDentist(Dentist model)
        {
            if (ModelState.IsValid)
            {
                model.Id = new Guid();
                await _dentist.AddAsync(model);
                return RedirectToAction(nameof(Index));
            }
            return View();
        }

        public IActionResult AllDentist()
        {
            IEnumerable<Dentist> allDentist = _dentist.AllDentistsAsync();
            return View(allDentist);
        }
    }
}

SmartToothWebProject/SmartTooth/Controllers/FacilitController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace SmartTooth.Controllers
{
    public class FacilitController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Facility()
        {
            ViewBag.Facility = DateTime.Now;
            return View();
        }
    }
}

SmartToothWebProject/SmartTooth/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SmartTooth.Models;

namespace SmartTooth.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SmartToothWebProject/SmartTooth/Views/Dentist/AllDentist.cshtml
@model IEnumerable<Dentist>


@{
    ViewData["Title"] = "AllDentist";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>AllDentist</h2>

<div class="dentistForm ">
    @{
        foreach (var dentist in Model)
        {
            <div class="dentsitItem">
                <p class="PValue">
                    @dentist.Name
                </p>

                <p class="PValue">
                    @dentist.LastName
                </p>

                <p class="PValue">
                    @dentist.Number
                </p>

                <p class="PValue">
                    @dentist.Popularity
                </p>

                <p class="PValue">
                    <a href="mailto: @dentist.Email">EMail</a>
                </p>

                <p class="PValue">
                    <a href="@dentist.FacebookUrl">FacebookUrl</a>
                </p>

                <p class="PValue">
                    @dentist.Description
                </p>

                <p class="PValue">
                    @dentist.Popularity
                </p>

                <a asp-action="Edit" asp-route-id="@dentist.Id">Edit</a>

            </div>

        }
    }
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>

SmartToothWebProject/SmartTooth/Views/Dentist/CreateDentist.cshtml
@model Dentist
@{
    ViewData["Title"] = "CreateDentist";
}


<h2>CreateDentist</h2>

<div>
    <form asp-action="CreateDentist" asp-controller="Dentist" method="post">
        <div asp-validation-summary="All">
            <div>
                <input asp-for="Name" placeholder="Name" type="text" name="name" />
            </div>
            <div>
                <input asp-for="LastName" placeholder="LastName" type="text" name="LastName" />
            </div>
            <div>
                <input asp-for="Description" placeholder="Description" type="text" name="Description" />
            </div>
            <div>
                <input asp-for="Specialization" placeholder="Specialization" type="text" name="Specialization" />
            </div>
            <div>
                <input asp-for="Email" placeholder="Email" type="email" name="Email" />
            </div>
            <div>
                <input asp-for="Number" placeholder="077-11-11-11" type="tel" pattern="[0-9]{3}-[0-9]{2}-[0-9]{2}-[0-9]{2}" name="Number" />
            </div>
            <div>
                <input asp-for="FacebookUrl" placeholder="FacebookUrl" type="url" name="FacebookUrl" />
            </div>
            <input type="submit" name="FacebookUrl" />
        </div>
    </form>
</div>

SmartToothWebProject/SmartTooth/Views/Dentist/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h2>
    @ViewBag.MyModel;
    Index
</h2>

SmartToothWebProject/SmartTooth/Views/Facilit/Facility.cshtml
@{
    ViewData["Title"] = "Facility";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@ViewBag.Facility;
<h2>Facility</h2>

SmartToothWebProject/SmartTooth/Views/Facilit/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<div class="dentsitItem">
    <p class="PValue">
        Բարի գալուստ «SmartTooth – Հայաստանի ատամնաբուժարաններ» ինֆորմացիոն պորտալ:

        Ատամնաբուժությունը Հայաստանում և ամբողջ աշխարհում զարգանում է բուռն տեմպերով, իսկ մենք, առօրյա հոգսերով ծանրաբեռնված, հաճախ բոլորովին մոռանում ենք մեր առողջության մասին, սակայն՝ իզուր:

        Այժմ Հայաստանի ատամնաբուժարանները համախմբած պորտալի էջերում դուք կարող եք մկնիկի մեկ հարվածով բազմաթիվ ատամնաբուժական կենտրոններից ընտրել ամենահարմարը Ձեզ համար:

        Դուք կարող եք դիտել Ձեզ դուր եկած ատամնաբուժարանի ամբողջական նկարագրությունը, տեսնել նաև Ձեր ապագա բժշկի լուսանկարն ու տեղեկանալ նրա մասնագիտական ստաժի մասին, համոզվել, որ Ձեր ապագա ատամնաբուժարանում աշխատում են իրենց գործի վարպետները: Մենք ջանացել ենք մեր ատամնաբուժական պորտալը դարձնել օգտակար և հետաքրքիր կայք Ձեզ համար:

        Ինտերնետային ցանցից օգտվող հարգելի այցելուներ, ատամնաբուժարանների հարմարավետ որոնում բազմաթիվ տարբերակներով.

        Ըստ ծառայությունների. որոնումների արդյունքում կտեսնեք, թե ինչպիսի ատամնաբուժարաններում և ինչ գներով կարող եք ստանալ այս կամ այն ծառայությունները: Ֆիլտրերի օգնությամբ կարող եք ոչ միայն գտնել մոտակա ատամնաբուժարանը, այլ նաև համակարգել գնային որոնումների արդյունքները:Ըստ բնակության վայրի. ընտրում եք շրջանն ու փողոցը, և որոնման արդյունքում կարող եք տեսնել այդ փողոցի վրա տեղակայված ատամնաբուժարանների ամբողջ ցուցակը:Քարտեզի օգնությամբ. քարտեզի վրա նշում եք Ձեր գտնվելու վայրը և ատամնաբուժարանների մաքսիմալ հեռավորությունը ձեզանից: Որոնումների արդյունքում կտեսնեք բոլոր այն ատամնաբուժարանները, որոնք համապատասխանում են Ձեր նշած չափանիշներին:

        Մեր կայքի այցելուները կարող են ստանալ զեղչեր: Պարզապես ընտրեք զեղչ ներկայացնող ատամնաբուժարանը, ստացեք կտրոնը և բուժվեք զեղչով:



        Ինչպես նաև «SmartTooth» պորտալի միջոցով Դուք կարող եք օնլայն գրանցվել բժշկի մոտ ընդունելության: Ատամնաբույժների օնլայն կոնսուլտացիան բոլոր ցանկացողների համար մեր պորտալում անվճար է:	Ձեր հարցերին կպատասխանեն հեղինակավոր բժիշկներ:	«SmartTooth»–ը «»–ի բազմաթիվ նախագծերից մեկն է:


        Ցանկանում ենք Ձեզ առողջ և ամուր ատամներ:
    </p>
</div>

SmartToothWebProject/SmartTooth/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>
    Use this area to provide additional information.
</p>

SmartToothWebProject/SmartTooth/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

SmartToothWebProject/SmartTooth/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<div class="TopHome">
    <img class="imgtop" src="https://d2v9y0dukr6mq2.cloudfront.net/video/thumbnail/Ha0T59ZIiq18yt35/teeth-care-infographics-animation-dentist-icon-in-teeth-caring-icons-circle_rn_nycf6_thumbnail-full01.png" alt="Alternate Text" />
    <a asp-controller="Dentist" asp-action="AllDentist"  class="ParagText">
        <div class="OneHome">
            <p class="ParagText">Մեր Մասնագետները</p>
            <img class="imgMasnaget" src="https://irp-cdn.multiscreensite.com/7679306d/dms3rep/multi/mobile/icon_02-360x360.png" alt="Alternate Text" />

            <p class="ParagTextCenter">
                Ինչպես նաև «SmartTooth» պորտալի միջոցով Դուք կարող եք օնլայն գրանցվել բժշկի մոտ ընդունելության:
                Ատամնաբույժների օնլայն կոնսուլտացիան բոլոր ցանկացողների համար մեր պորտալում անվճար է:	
                Ձեր հարցերին կպատասխանեն հեղինակավոր բժիշկներ:	«SmartTooth»–ը «»–ի բազմաթիվ նախագծերից մեկն է:

            </p>
        </div>
    </a>
    <a asp-controller="Facilit" asp-action="Index" class="ParagText">
        <div class="OneHome">
            <p class="ParagText">Մեր Ծառայությունները</p>
            <img class="imgMasnaget" src="http://www.dalmio-dent.md/wp-content/uploads/2016/11/icon_03-360x360.png" alt="Alternate Text" />
            <p class="ParagTextCenter">
                Ըստ ծառայությունների. որոնումների արդյունքում կտեսնեք, թե ինչպիսի ատամնաբուժարաններում և ինչ գներով կարող եք ստանալ այս կամ այն ծառայությունները: 
                Ֆիլտրերի օգնությամբ կարող եք ոչ միայն գտնել մոտակա ատամնաբուժարանը, այլ նաև համակարգել գնային որոնումների արդյունքները:
            </p>
        </div>
    </a>
    <a href="#" class="ParagText">
        <div class="OneHome">
            <p class="ParagText">Մեր Հաճախորդները</p>
            <img class="imgMasnaget" src="https://www.namg.net/wp-content/uploads/2017/09/patients-icon.png" alt="Alternate Text" />

            <p class="ParagTextCenter">
                What is Lorem Ipsum?
                Lorem Ipsum is simply dummy text of the printing and typesetting industry.
                Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
                when an unknown printer took a galley of type and scrambled it to make a type specimen book.
            </p>
        </div>
    </a>
</div>

SmartToothWebProject/SmartTooth/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SmartTooth</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">SmartTooth</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Dentist" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Dentist" asp-action="CreateDentist">Create</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - SmartTooth</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>